name: Build VM Patcher Image
on:
  - pull_request
  - push

jobs:
  build-vm:
    name: Build VM
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils

      - uses: actions/checkout@v4

      - name: Download Windows deps
        run: |
          cd win
          ./download_deps.sh

      - name: Build patcher image
        run: |
          cd win
          ./build_vm.sh

      # This is needed because the release action
      # Doesn't do it on it's own
      - name: Zip up release package
        if: github.ref_type == 'tag'
        # GitHub limits the size of release artifacts
        run: zip -r -s 2000M ssmm_build_vm.zip win/

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          generate_release_notes: true
          prerelease: true
          files: ssmm_build_vm.z*

      - name: Archive objects
        # Skip archive if running on act
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: ssmm_build_vm
          path: win