name: Build Release Outputs
on:
  - pull_request
  - push

jobs:
  build-vm:
    name: Build VM
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils

      - uses: actions/checkout@v4

      - name: Download Windows deps
        run: |
          cd win
          ./download_deps.sh

      - name: Build patcher image
        run: |
          cd win
          ./build_vm.sh

      # This is needed because the release action
      # Doesn't do it on it's own
      - name: Zip up release package
        if: github.ref_type == 'tag'
        # GitHub limits the size of release artifacts
        run: zip -r -s 2000M ssmm_build_vm_${{ github.ref_name }}.zip win/

      - name: Release
        # TODO: unpin version when this is resolved
        # https://github.com/softprops/action-gh-release/issues/627
        uses: softprops/action-gh-release@v2.2.2
        if: github.ref_type == 'tag'
        with:
          generate_release_notes: true
          prerelease: true
          files: ssmm_build_vm_${{ github.ref_name }}.z*

      - name: Archive objects
        # Skip archive if running on act
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: ssmm_build_vm
          path: win

  build-pnach:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: cache-${{ runner.os }}-nix-store-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: cache-${{ runner.os }}-nix-store-

      - name: Build pnaches
        run: |
          nix build .#debug-patches
          cp result/SCPS-15115_8EFDBAEB.pnach .
          # HACK: We cannot know the patched CRC without access to the original elf/ISO.
          # Instead, just hardcode the new filename. This will have to be updated
          # if the production patches ever change
          cp SCPS-15115_8EFDBAEB.pnach SCPS-15115_AABE2016.pnach

      - name: Release
        # TODO: unpin version when this is resolved
        # https://github.com/softprops/action-gh-release/issues/627
        uses: softprops/action-gh-release@v2.2.2
        if: github.ref_type == 'tag'
        with:
          generate_release_notes: true
          prerelease: true
          files: SCPS-15115_*.pnach

      - name: Archive objects
        # Skip archive if running on act
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: SCPS-15115_pnaches
          path: SCPS-15115_*.pnach
